import type { Metadata } from "next";
import { Roboto } from "next/font/google";
import "./globals.css";
import Navbar from "@/components/navbar/navbar";

// Importing Roboto font with multiple weights (400, 500, 600, 700)
const roboto = Roboto({
  variable: "--font-roboto",
  weight: ["400", "500", "600", "700"],  // Regular (400), Medium (500), Semi-Bold (600), Bold (700)
  style: ["normal"],    // Only normal style (you can add italic if you need it)
  subsets: ["latin"],   // You can add other subsets like latin-ext if needed
});

export const metadata: Metadata = {
  title: "Connector",
  description: "Generated by US Connector developers",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${roboto.variable} antialiased`}>
        <Navbar />
        {children}
      </body>
    </html>
  );
}
