import type { Metadata } from "next";
import { Poppins} from "next/font/google";
import "./globals.css";
import { ThemeProvider } from "@/app/(dashboard)/context/ThemeContext";
import { SidebarProvider } from "@/app/(dashboard)/context/SidebarContext";
import { Toaster } from "react-hot-toast";


const poppins = Poppins({ 
  variable: "--font-poppins",
  weight: ["400","500", "600", "700","800"],  // Regular (400), Medium (500), Semi-Bold (600), Bold (700)
  style: ["normal"],    // Only normal style (you can add italic if you need it)
  subsets: ["latin"],   // You can add other subsets like latin-ext if needed
});

export const metadata: Metadata = {
  title: "Connector",
  icons:{
    icon: "/us-connector.png",
    shortcut: "/us-connector.png",
    apple: "/us-connector.png",
  },
  description: "Generated by US Connector developers",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${poppins.variable} antialiased bg-white text-black dark:bg-gray-900 dark:text-white`}>
          <ThemeProvider>
          <SidebarProvider>{children}</SidebarProvider>
        </ThemeProvider>
        <Toaster position="top-right" />
      </body>
    </html>
  );
}
